In [1]:
import pandas as pd

In [2]:
url_prl = "https://www.football-data.co.uk/mmz4281/2526/E0.csv"
df = pd.read_csv(url_prl)

In [3]:
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [4]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 291 entries, 0 to 290
Columns: 132 entries, Div to BFECAHA
dtypes: float64(108), int64(16), str(8)
memory usage: 300.2 KB
None

In [5]:
display(df.describe())

,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
count,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000,...,291.000000,291.000000,210.000000,210.000000,291.000000,291.000000,291.000000,291.000000,291.000000,291.000000
mean,1.515464,1.257732,0.697595,0.515464,13.584192,11.027491,4.429553,3.841924,10.642612,11.041237,...,1.917010,1.931409,1.964762,1.966143,1.941409,1.960756,1.872199,1.889931,1.988729,2.001615
std,1.169557,1.104333,0.786499,0.758129,4.998168,4.596768,2.224709,2.112956,3.218927,3.354619,...,0.098937,0.098154,0.110116,0.111749,0.093121,0.089763,0.084462,0.086563,0.098950,0.098910
min,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,0.000000,0.000000,4.000000,3.000000,...,1.680000,1.650000,1.680000,1.680000,1.750000,1.750000,1.710000,1.700000,1.810000,1.740000
25%,1.000000,0.000000,0.000000,0.000000,10.500000,7.500000,3.000000,2.000000,8.000000,9.000000,...,1.850000,1.850000,1.880000,1.880000,1.855000,1.890000,1.805000,1.820000,1.910000,1.930000
50%,1.000000,1.000000,1.000000,0.000000,13.000000,11.000000,4.000000,4.000000,10.000000,11.000000,...,1.930000,1.930000,1.970000,1.950000,1.930000,1.970000,1.860000,1.890000,1.970000,2.010000
75%,2.000000,2.000000,1.000000,1.000000,16.000000,14.000000,6.000000,5.000000,13.000000,13.000000,...,2.000000,2.000000,2.040000,2.050000,2.030000,2.030000,1.940000,1.960000,2.060000,2.080000
max,5.000000,5.000000,3.000000,3.000000,35.000000,30.000000,11.000000,11.000000,20.000000,21.000000,...,2.200000,2.150000,2.320000,2.330000,2.350000,2.200000,2.100000,2.080000,2.320000,2.220000

In [9]:
print(df.columns.to_list())

['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BFDH', 'BFDD', 'BFDA', 'BMGMH', 'BMGMD', 'BMGMA', 'BVH', 'BVD', 'BVA', 'BWH', 'BWD', 'BWA', 'CLH', 'CLD', 'CLA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'BFEH', 'BFED', 'BFEA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'BFE>2.5', 'BFE<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'BFEAHH', 'BFEAHA', 'B365CH', 'B365CD', 'B365CA', 'BFDCH', 'BFDCD', 'BFDCA', 'BMGMCH', 'BMGMCD', 'BMGMCA', 'BVCH', 'BVCD', 'BVCA', 'BWCH', 'BWCD', 'BWCA', 'CLCH', 'CLCD', 'CLCA', 'LBCH', 'LBCD', 'LBCA', 'PSCH', 'PSCD', 'PSCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'BFECH', 'BFECD', 'BFECA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'BFEC>2.5', 'BFEC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA', 'BFECAHH', 'BFECAHA']

In [10]:
df.head(3).T

                    0            1           2
Div                E0           E0          E0
Date       15/08/2025   16/08/2025  16/08/2025
Time            20:00        12:30       15:00
HomeTeam    Liverpool  Aston Villa    Brighton
AwayTeam  Bournemouth    Newcastle      Fulham
...               ...          ...         ...
MaxCAHA          1.88          1.8        2.03
AvgCAHH          1.94         1.95         1.8
AvgCAHA          1.76         1.74        1.96
BFECAHH          2.14         2.14        1.91
BFECAHA          1.86         1.86        2.08

[132 rows x 3 columns]

In [20]:
missing_values = df.isnull().mean() *100
print("percentage of missing values:")
print(missing_values.sort_values(ascending=True).head(50))

percentage of missing values:
Div         0.0
Date        0.0
Time        0.0
HomeTeam    0.0
AwayTeam    0.0
FTHG        0.0
FTAG        0.0
FTR         0.0
HTHG        0.0
HTAG        0.0
HTR         0.0
Referee     0.0
HS          0.0
AS          0.0
HST         0.0
AST         0.0
HF          0.0
AF          0.0
HC          0.0
AC          0.0
HY          0.0
AY          0.0
HR          0.0
AR          0.0
B365H       0.0
B365D       0.0
B365A       0.0
BFDH        0.0
BFDD        0.0
BFDA        0.0
BMGMH       0.0
BMGMD       0.0
BMGMA       0.0
BVH         0.0
BVD         0.0
BVA         0.0
BWH         0.0
BWD         0.0
BWA         0.0
BFEA        0.0
BFED        0.0
BFEH        0.0
AvgA        0.0
AvgD        0.0
AvgH        0.0
MaxA        0.0
MaxD        0.0
MaxH        0.0
Avg>2.5     0.0
B365>2.5    0.0
dtype: float64

In [22]:
my_features = [
    'Date', 'Time', 'HomeTeam', 'AwayTeam', 
    'FTHG', 'FTAG', 'FTR', 
    'HTHG', 'HTAG', 'HTR',
    'HS', 'AS', 'HST', 'AST', 
    'HR', 'AR', 
    'B365H', 'B365D', 'B365A'
]

In [23]:
df_clean = df[my_features].copy()

In [25]:
rename_mapping = {
    'FTHG': 'home_goals',
    'FTAG': 'away_goals',
    'FTR': 'match_result',
    'HS': 'home_shots',
    'AS': 'away_shots',
    'HST': 'home_shots_target',
    'AST': 'away_shots_target',
    'HR': 'home_red_cards',
    'AR': 'away_red_cards'
}

In [26]:
df_clean.rename(columns=rename_mapping, inplace=True)

In [27]:
display(df_clean.head())

,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,match_result,HTHG,HTAG,HTR,home_shots,away_shots,home_shots_target,away_shots_target,home_red_cards,away_red_cards,B365H,B365D,B365A
0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,H,19,10,10,3,0,0,1.30,6.00,8.50
1,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,D,3,16,3,3,1,0,2.25,3.50,2.90
2,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,D,10,7,4,2,0,0,1.91,3.60,4.00
3,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,D,10,12,5,4,0,0,3.25,3.40,2.25
4,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,H,16,14,6,4,0,0,1.38,4.75,8.50

In [28]:
df_clean.to_csv('01_clean_data.csv', index=False)

In [29]:
missing_values_clean = df_clean.isnull().mean() *100
print("percentage of missing values in cleaned dataset:")
print(missing_values_clean)

percentage of missing values in cleaned dataset:
Date                 0.0
Time                 0.0
HomeTeam             0.0
AwayTeam             0.0
home_goals           0.0
away_goals           0.0
match_result         0.0
HTHG                 0.0
HTAG                 0.0
HTR                  0.0
home_shots           0.0
away_shots           0.0
home_shots_target    0.0
away_shots_target    0.0
home_red_cards       0.0
away_red_cards       0.0
B365H                0.0
B365D                0.0
B365A                0.0
dtype: float64